https://raw.githubusercontent.com/nkmwicz/data-for-students/refs/heads/main/soccer-players.csv

In [21]:
import pandas as pd 

url = 'https://raw.githubusercontent.com/nkmwicz/data-for-students/refs/heads/main/soccer-players.csv'

df = pd.read_csv(url)
df.head()

,player_id,first_name,last_name,name,last_season,current_club_id,player_code,country_of_birth,city_of_birth,country_of_citizenship,...,foot,height_in_cm,contract_expiration_date,agent_name,image_url,url,current_club_domestic_competition_id,current_club_name,market_value_in_eur,highest_market_value_in_eur
0,10,Miroslav,Klose,Miroslav Klose,2015,398,miroslav-klose,Poland,Opole,Germany,...,right,184.0,NaN,ASBW Sport Marketing,https://img.a.transfermarkt.technology/portrai...,https://www.transfermarkt.co.uk/miroslav-klose...,IT1,Società Sportiva Lazio S.p.A.,1000000.0,30000000.0
1,26,Roman,Weidenfeller,Roman Weidenfeller,2017,16,roman-weidenfeller,Germany,Diez,Germany,...,left,190.0,NaN,Neubauer 13 GmbH,https://img.a.transfermarkt.technology/portrai...,https://www.transfermarkt.co.uk/roman-weidenfe...,L1,Borussia Dortmund,750000.0,8000000.0
2,65,Dimitar,Berbatov,Dimitar Berbatov,2015,1091,dimitar-berbatov,Bulgaria,Blagoevgrad,Bulgaria,...,NaN,NaN,NaN,CSKA-AS-23 Ltd.,https://img.a.transfermarkt.technology/portrai...,https://www.transfermarkt.co.uk/dimitar-berbat...,GR1,Panthessalonikios Athlitikos Omilos Konstantin...,1000000.0,34500000.0
3,77,NaN,Lúcio,Lúcio,2012,506,lucio,Brazil,Brasília,Brazil,...,NaN,NaN,NaN,NaN,https://img.a.transfermarkt.technology/portrai...,https://www.transfermarkt.co.uk/lucio/profil/s...,IT1,Juventus Football Club,200000.0,24500000.0
4,80,Tom,Starke,Tom Starke,2017,27,tom-starke,East Germany (GDR),Freital,Germany,...,right,194.0,NaN,IFM,https://img.a.transfermarkt.technology/portrai...,https://www.transfermarkt.co.uk/tom-starke/pro...,L1,FC Bayern München,100000.0,3000000.0

In [ ]:
def convert_height(cm) -> float:
    '''
    Convert height from centimeters to feet.
    
    ARGS:
    cm(int): the num of centimeters 
    RETURNS:
    feet (float): the num of feet 
    '''
    return (cm * 0.393701) / 12

In [23]:
df['height_in_ft'] = df['height_in_cm'].apply(convert_height)
df['height_in_ft']

0        6.036749
1        6.233599
2             NaN
3             NaN
4        6.364833
           ...
32398    5.839898
32399    5.905515
32400    5.380580
32401         NaN
32402         NaN
Name: height_in_ft, Length: 32403, dtype: float64

In [24]:
df.describe()

,player_id,last_season,current_club_id,height_in_cm,market_value_in_eur,highest_market_value_in_eur,height_in_ft
count,3.240300e+04,32403.000000,32403.000000,30059.000000,3.086900e+04,3.086900e+04,30059.000000
mean,3.445789e+05,2019.337777,4809.252045,182.291161,1.611350e+06,3.675045e+06,5.980684
std,2.806831e+05,3.965914,11601.982978,6.971224,6.362017e+06,9.653897e+06,0.228715
min,1.000000e+01,2012.000000,3.000000,17.000000,1.000000e+04,1.000000e+04,0.557743
25%,1.066980e+05,2016.000000,403.000000,178.000000,1.000000e+05,2.750000e+05,5.839898
50%,2.824210e+05,2020.000000,1071.000000,183.000000,2.500000e+05,8.000000e+05,6.003940
75%,5.242085e+05,2023.000000,3060.000000,187.000000,7.000000e+05,2.800000e+06,6.135174
max,1.309800e+06,2024.000000,110302.000000,207.000000,2.000000e+08,2.000000e+08,6.791342

In [25]:
df['height_in_cm'].std()

6.971224376399549

In [28]:
df['height_in_ft'].var()
df['height_in_ft'].std()

0.22871483401772097

In [30]:
df['height_in_ft'].mean()

np.float64(5.980684355462036)

In [32]:
df['height_in_cm'].median()

183.0

In [34]:
range = df['height_in_cm'].max() - df['height_in_cm'].min()
range

190.0

In [37]:
df['height_in_cm'].skew()

np.float64(-1.7751475048518246)

In [39]:
from scipy import stats
sk = stats.skew(df['height_in_cm'], nan_policy = 'omit')
sk

np.float64(-1.7750589204621978)

In [40]:
df['height_in_cm'].kurt()

np.float64(40.3723954752419)

In [41]:
stats.kurtosis(df['height_in_cm'].dropna())

np.float64(40.36548066183285)

In [45]:
def eda(df):
    '''
    Evaluate basic statistics on a dataframe
    
    ARGS:  
        df (pandas.DataFrame): the dataframe to be evaluated
    Returns:
        None
    '''
    print(f"('='*5)DF Shape: {df.shape}{'='*5}")
    num_cols = []
    cat_cols = []
    for col in df.columns:
        if pd.api.types.is_numeric_dtype(df[col]):
            num_cols.append(df[col])
        else: 
            cat_cols.append(df[col])
    print(f"{'*'*3}Numerical Columns{'*'*3}")
    for col in num_cols:
        print(col)
        print(f"\tMin: {df[col].min()}")
        print (f"\tMax: {df[col].max()}")

In [44]:
eda(df)

('='*5)DF Shape: (32403, 24)=====
[0             10
1             26
2             65
3             77
4             80
          ...
32398    1302421
32399    1306131
32400    1306851
32401    1309504
32402    1309800
Name: player_id, Length: 32403, dtype: int64, 0        2015
1        2017
2        2015
3        2012
4        2017
         ...
32398    2024
32399    2024
32400    2024
32401    2024
32402    2024
Name: last_season, Length: 32403, dtype: int64, 0         398
1          16
2        1091
3         506
4          27
         ...
32398    6992
32399    2503
32400    5724
32401    2778
32402    2778
Name: current_club_id, Length: 32403, dtype: int64, 0        184.0
1        190.0
2          NaN
3          NaN
4        194.0
         ...
32398    178.0
32399    180.0
32400    164.0
32401      NaN
32402      NaN
Name: height_in_cm, Length: 32403, dtype: float64, 0        1000000.0
1         750000.0
2        1000000.0
3         200000.0
4         100000.0
           ...
32398     100000.0
32399     100000.0
32400          NaN
32401          NaN
32402          NaN
Name: market_value_in_eur, Length: 32403, dtype: float64, 0        30000000.0
1         8000000.0
2        34500000.0
3        24500000.0
4         3000000.0
            ...
32398      100000.0
32399      100000.0
32400           NaN
32401           NaN
32402           NaN
Name: highest_market_value_in_eur, Length: 32403, dtype: float64, 0        6.036749
1        6.233599
2             NaN
3             NaN
4        6.364833
           ...
32398    5.839898
32399    5.905515
32400    5.380580
32401         NaN
32402         NaN
Name: height_in_ft, Length: 32403, dtype: float64] [0        Miroslav
1           Roman
2         Dimitar
3             NaN
4             Tom
           ...
32398         NaN
32399       Fábio
32400       Hakim
32401      Diallo
32402      Issaka
Name: first_name, Length: 32403, dtype: object, 0               Klose
1        Weidenfeller
2            Berbatov
3               Lúcio
4              Starke
             ...
32398       João Neto
32399           Sambú
32400        Sulemana
32401        Sanoussi
32402           Seidu
Name: last_name, Length: 32403, dtype: object, 0            Miroslav Klose
1        Roman Weidenfeller
2          Dimitar Berbatov
3                     Lúcio
4                Tom Starke
                ...
32398             João Neto
32399           Fábio Sambú
32400        Hakim Sulemana
32401       Diallo Sanoussi
32402          Issaka Seidu
Name: name, Length: 32403, dtype: object, 0            miroslav-klose
1        roman-weidenfeller
2          dimitar-berbatov
3                     lucio
4                tom-starke
                ...
32398             joao-neto
32399           fabio-sambu
32400        hakim-sulemana
32401       diallo-sanoussi
32402          issaka-seidu
Name: player_code, Length: 32403, dtype: object, 0                    Poland
1                   Germany
2                  Bulgaria
3                    Brazil
4        East Germany (GDR)
                ...
32398                   NaN
32399              Portugal
32400                 Ghana
32401                   NaN
32402                   NaN
Name: country_of_birth, Length: 32403, dtype: object, 0              Opole
1               Diez
2        Blagoevgrad
3           Brasília
4            Freital
            ...
32398            NaN
32399       Barreiro
32400       Techiman
32401            NaN
32402            NaN
Name: city_of_birth, Length: 32403, dtype: object, 0              Germany
1              Germany
2             Bulgaria
3               Brazil
4              Germany
             ...
32398           Brazil
32399         Portugal
32400            Ghana
32401    Cote d'Ivoire
32402            Ghana
Name: country_of_citizenship, Length: 32403, dtype: object, 0        1978-06-09 00:00:00
1        1980-08-06 00:00:00
2        1981-01-30 00:00:00
3        1978-05-08 00:00:00
4        1981-03-18 00:00:00
                ...
32398    2003-02-04 00:00:00
32399    2007-09-06 00:00:00
32400    2005-02-19 00:00:00
32401    2006-01-01 00:00:00
32402    2006-06-05 00:00:00
Name: date_of_birth, Length: 32403, dtype: object, 0            Centre-Forward
1                Goalkeeper
2            Centre-Forward
3               Centre-Back
4                Goalkeeper
                ...
32398          Right Winger
32399        Centre-Forward
32400           Left Winger
32401    Attacking Midfield
32402             Left-Back
Name: sub_position, Length: 32403, dtype: object, 0            Attack
1        Goalkeeper
2            Attack
3          Defender
4        Goalkeeper
            ...
32398        Attack
32399        Attack
32400        Attack
32401      Midfield
32402      Defender
Name: position, Length: 32403, dtype: object, 0        right
1         left
2          NaN
3          NaN
4        right
         ...
32398    right
32399    right
32400     both
32401      NaN
32402     left
Name: foot, Length: 32403, dtype: object, 0                        NaN
1                        NaN
2                        NaN
3                        NaN
4                        NaN
                ...
32398                    NaN
32399    2027-06-30 00:00:00
32400    2026-06-30 00:00:00
32401                    NaN
32402                    NaN
Name: contract_expiration_date, Length: 32403, dtype: object, 0        ASBW Sport Marketing
1            Neubauer 13 GmbH
2             CSKA-AS-23 Ltd.
3                         NaN
4                         IFM
                 ...
32398          ADRIANO SPORTS
32399                     NaN
32400                     NaN
32401                     NaN
32402             CAA Stellar
Name: agent_name, Length: 32403, dtype: object, 0        https://img.a.transfermarkt.technology/portrai...
1        https://img.a.transfermarkt.technology/portrai...
2        https://img.a.transfermarkt.technology/portrai...
3        https://img.a.transfermarkt.technology/portrai...
4        https://img.a.transfermarkt.technology/portrai...
                               ...
32398    https://img.a.transfermarkt.technology/portrai...
32399    https://img.a.transfermarkt.technology/portrai...
32400    https://img.a.transfermarkt.technology/portrai...
32401    https://img.a.transfermarkt.technology/portrai...
32402    https://img.a.transfermarkt.technology/portrai...
Name: image_url, Length: 32403, dtype: object, 0        https://www.transfermarkt.co.uk/miroslav-klose...
1        https://www.transfermarkt.co.uk/roman-weidenfe...
2        https://www.transfermarkt.co.uk/dimitar-berbat...
3        https://www.transfermarkt.co.uk/lucio/profil/s...
4        https://www.transfermarkt.co.uk/tom-starke/pro...
                               ...
32398    https://www.transfermarkt.co.uk/joao-neto/prof...
32399    https://www.transfermarkt.co.uk/fabio-sambu/pr...
32400    https://www.transfermarkt.co.uk/hakim-sulemana...
32401    https://www.transfermarkt.co.uk/diallo-sanouss...
32402    https://www.transfermarkt.co.uk/issaka-seidu/p...
Name: url, Length: 32403, dtype: object, 0         IT1
1          L1
2         GR1
3         IT1
4          L1
         ...
32398    UKR1
32399     PO1
32400     DK1
32401     DK1
32402     DK1
Name: current_club_domestic_competition_id, Length: 32403, dtype: object, 0                            Società Sportiva Lazio S.p.A.
1                                        Borussia Dortmund
2        Panthessalonikios Athlitikos Omilos Konstantin...
3                                   Juventus Football Club
4                                        FC Bayern München
                               ...
32398                           ZAO FK Chornomorets Odessa
32399                               Boavista Futebol Clube
32400                                 Randers Fodbold Club
32401                            Fodbold Club Nordsjælland
32402                            Fodbold Club Nordsjælland
Name: current_club_name, Length: 32403, dtype: object]